export const ADD_ING = 'ADD_ING';
export const REMOVE_ING = 'REMOVE_ING';
export const SET_ING = 'SET_ING';
export const FETCH_ING_FAILED = 'FETCH_ING_FAILED';

export const PURCHASE_TORTILLA_BEGIN = 'PURCHASE_TORTILLA_BEGIN';
export const PURCHASE_TORTILLA_SUCCESS = 'PURCHASE_TORTILLA_SUCCESS';
export const PURCHASE_TORTILLA_FAILED = 'PURCHASE_TORTILLA_FAILED';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORD_BEGIN = 'FETCH_ORD_BEGIN';
export const FETCH_ORD_SUCCESS = 'FETCH_ORD_SUCCESS';
export const FETCH_ORD_FAILED = 'FETCH_ORD_FAILED';

export const AUTH_BEGIN = 'AUTH_BEGIN';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';