export const ADD_ING = 'ADD_ING';
export const REMOVE_ING = 'REMOVE_ING';
export const SET_ING = 'SET_ING';
export const FETCH_ING_FAILED = 'FETCH_ING_FAILED';

export const PURCHASE_TORTILLA_START = 'PURCHASE_TORTILLA_BEGIN'
export const PURCHASE_TORTILLA_SUCCESS = 'PURCHASE_TORTILLA_SUCCESS';
export const PURCHASE_TORTILLA_FAIL = 'PURCHASE_TORTILLA_FAIL';